services:
  - type: web
    name: real-life-among-us-beta
    runtime: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: .
    plan: free
    region: frankfurt
    healthCheckPath: /health
