services:
  - type: web
    name: real-life-among-us-beta
    runtime: docker
    rootDir: server
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: frankfurt
    healthCheckPath: /health
